name: Android CI

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    # https://github.com/ilharp/sign-android-release
    - uses: ilharp/sign-android-release@v2
      name: Sign APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        buildToolsVersion: 34.0.0
    - name: Rename APK
      run: mv ${{steps.sign_app.outputs.signedFile}} "cr-calculator-app-${{ github.ref_name }}.apk"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: "app.apk"
        path: ${{steps.sign_app.outputs.signedFile}}
        retention-days: 90
    - name: Create release
      run: gh release create ${{ github.ref_name }} "cr-calculator-app-${{ github.ref_name }}.apk" --title "Version ${{ github.ref_name }} release"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
